package edu.suse.bookstore.mapper;

import edu.suse.bookstore.domain.BookPress;
import edu.suse.bookstore.domain.BookPressExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface BookPressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    long countByExample(BookPressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByExample(BookPressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insert(BookPress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insertSelective(BookPress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    List<BookPress> selectByExample(BookPressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    BookPress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") BookPress record, @Param("example") BookPressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExample(@Param("record") BookPress record, @Param("example") BookPressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKeySelective(BookPress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKey(BookPress record);
}