package edu.suse.bookstore.mapper;

import edu.suse.bookstore.domain.BookAuthor;
import edu.suse.bookstore.domain.BookAuthorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookAuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    long countByExample(BookAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByExample(BookAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insert(BookAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insertSelective(BookAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    List<BookAuthor> selectByExample(BookAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    BookAuthor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") BookAuthor record, @Param("example") BookAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExample(@Param("record") BookAuthor record, @Param("example") BookAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKeySelective(BookAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKey(BookAuthor record);
}