package edu.suse.bookstore.mapper;

import edu.suse.bookstore.domain.BookImageExample;
import edu.suse.bookstore.domain.BookImageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    long countByExample(BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByExample(BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByPrimaryKey(BookImageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insert(BookImageKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insertSelective(BookImageKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    List<BookImageKey> selectByExample(BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") BookImageKey record, @Param("example") BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExample(@Param("record") BookImageKey record, @Param("example") BookImageExample example);
}