package edu.suse.bookstore.mapper;

import edu.suse.bookstore.domain.OrderBook;
import edu.suse.bookstore.domain.OrderBookExample;
import edu.suse.bookstore.domain.OrderBookKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    long countByExample(OrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByExample(OrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByPrimaryKey(OrderBookKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insert(OrderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insertSelective(OrderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    List<OrderBook> selectByExample(OrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    OrderBook selectByPrimaryKey(OrderBookKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderBook record, @Param("example") OrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExample(@Param("record") OrderBook record, @Param("example") OrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKeySelective(OrderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKey(OrderBook record);
}