package edu.suse.bookstore.mapper;

import edu.suse.bookstore.domain.PermissionType;
import edu.suse.bookstore.domain.PermissionTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    long countByExample(PermissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int deleteByExample(PermissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int deleteByPrimaryKey(Integer ptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int insert(PermissionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int insertSelective(PermissionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    List<PermissionType> selectByExample(PermissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") PermissionType record, @Param("example") PermissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int updateByExample(@Param("record") PermissionType record, @Param("example") PermissionTypeExample example);
}