package edu.suse.bookstore.mapper;

import edu.suse.bookstore.domain.RolePermissionExample;
import edu.suse.bookstore.domain.RolePermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_role_per
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_role_per
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_role_per
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_role_per
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int insert(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_role_per
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int insertSelective(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_role_per
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    List<RolePermissionKey> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_role_per
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_role_per
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    int updateByExample(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);
}