package edu.suse.bookstore.mapper;

import edu.suse.bookstore.domain.ShopCart;
import edu.suse.bookstore.domain.ShopCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCartMapper extends ShopCartMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    long countByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insert(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insertSelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    List<ShopCart> selectByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    ShopCart selectByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExample(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKeySelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKey(ShopCart record);
}