package edu.suse.bookstore.mapper;

import edu.suse.bookstore.domain.UploadImage;
import edu.suse.bookstore.domain.UploadImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UploadImageMapper extends UploadImageMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    long countByExample(UploadImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByExample(UploadImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insert(UploadImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int insertSelective(UploadImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    List<UploadImage> selectByExample(UploadImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    UploadImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") UploadImage record, @Param("example") UploadImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByExample(@Param("record") UploadImage record, @Param("example") UploadImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKeySelective(UploadImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_image
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    int updateByPrimaryKey(UploadImage record);
}