package edu.suse.bookstore.domain;

import java.io.Serializable;

public class BookType extends CheckedExtends implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.type
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_type
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.id
     *
     * @return the value of book_type.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.id
     *
     * @param id the value for book_type.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.type
     *
     * @return the value of book_type.type
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.type
     *
     * @param type the value for book_type.type
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}