package edu.suse.bookstore.domain;

import java.io.Serializable;

public class BookAuthor extends CheckedExtends implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_author.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_author.author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_author.id
     *
     * @return the value of book_author.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_author.id
     *
     * @param id the value for book_author.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_author.author
     *
     * @return the value of book_author.author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_author.author
     *
     * @param author the value for book_author.author
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }
}