package edu.suse.bookstore.domain;

import java.io.Serializable;

public class BookImageKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fk_book_img.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fk_book_img.img_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fk_book_img
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fk_book_img.book_id
     *
     * @return the value of fk_book_img.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fk_book_img.book_id
     *
     * @param bookId the value for fk_book_img.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fk_book_img.img_id
     *
     * @return the value of fk_book_img.img_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fk_book_img.img_id
     *
     * @param imgId the value for fk_book_img.img_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }
}