package edu.suse.bookstore.domain;

import java.io.Serializable;

public class BookPress extends CheckedExtends implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_press.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_press.press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_press.id
     *
     * @return the value of book_press.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_press.id
     *
     * @param id the value for book_press.id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_press.press
     *
     * @return the value of book_press.press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_press.press
     *
     * @param press the value for book_press.press
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }
}