package edu.suse.bookstore.domain;

import java.io.Serializable;

public class OrderBookKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fk_order_book.order_number
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fk_order_book.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fk_order_book.order_number
     *
     * @return the value of fk_order_book.order_number
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fk_order_book.order_number
     *
     * @param orderNumber the value for fk_order_book.order_number
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fk_order_book.book_id
     *
     * @return the value of fk_order_book.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fk_order_book.book_id
     *
     * @param bookId the value for fk_order_book.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}