package edu.suse.bookstore.domain;

import java.io.Serializable;

public class OrderBook extends OrderBookKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fk_order_book.quant
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer quant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fk_order_book
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fk_order_book.quant
     *
     * @return the value of fk_order_book.quant
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getQuant() {
        return quant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fk_order_book.quant
     *
     * @param quant the value for fk_order_book.quant
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setQuant(Integer quant) {
        this.quant = quant;
    }
}