package edu.suse.bookstore.domain;

import java.io.Serializable;

public class PermissionType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_type.pt_id
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    private Integer ptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission_type
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_type.pt_id
     *
     * @return the value of permission_type.pt_id
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    public Integer getPtId() {
        return ptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_type.pt_id
     *
     * @param ptId the value for permission_type.pt_id
     *
     * @mbg.generated Sun May 24 01:03:01 CST 2020
     */
    public void setPtId(Integer ptId) {
        this.ptId = ptId;
    }
}