package edu.suse.bookstore.domain;

import java.io.Serializable;

public class Role extends RoleExt implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.role_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.role
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.display_name
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_role
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.role_id
     *
     * @return the value of bs_role.role_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.role_id
     *
     * @param roleId the value for bs_role.role_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.role
     *
     * @return the value of bs_role.role
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.role
     *
     * @param role the value for bs_role.role
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.display_name
     *
     * @return the value of bs_role.display_name
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.display_name
     *
     * @param displayName the value for bs_role.display_name
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }
}