package edu.suse.bookstore.domain;

import java.io.Serializable;

public class ShopCart extends ShopCartExt implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.cart_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.quantity
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_cart
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.cart_id
     *
     * @return the value of shop_cart.cart_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.cart_id
     *
     * @param cartId the value for shop_cart.cart_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.user_id
     *
     * @return the value of shop_cart.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.user_id
     *
     * @param userId the value for shop_cart.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.book_id
     *
     * @return the value of shop_cart.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.book_id
     *
     * @param bookId the value for shop_cart.book_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.quantity
     *
     * @return the value of shop_cart.quantity
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.quantity
     *
     * @param quantity the value for shop_cart.quantity
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}