package edu.suse.bookstore.domain;

import java.io.Serializable;
import java.util.Date;

public class User extends UserExt implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.username
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.password
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.nick_name
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.phone
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.email
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.create_time
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.last_login_time
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.status
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_user
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.user_id
     *
     * @return the value of bs_user.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.user_id
     *
     * @param userId the value for bs_user.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.username
     *
     * @return the value of bs_user.username
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.username
     *
     * @param username the value for bs_user.username
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.password
     *
     * @return the value of bs_user.password
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.password
     *
     * @param password the value for bs_user.password
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.nick_name
     *
     * @return the value of bs_user.nick_name
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.nick_name
     *
     * @param nickName the value for bs_user.nick_name
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.phone
     *
     * @return the value of bs_user.phone
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.phone
     *
     * @param phone the value for bs_user.phone
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.email
     *
     * @return the value of bs_user.email
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.email
     *
     * @param email the value for bs_user.email
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.create_time
     *
     * @return the value of bs_user.create_time
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.create_time
     *
     * @param createTime the value for bs_user.create_time
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.last_login_time
     *
     * @return the value of bs_user.last_login_time
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.last_login_time
     *
     * @param lastLoginTime the value for bs_user.last_login_time
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.status
     *
     * @return the value of bs_user.status
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.status
     *
     * @param status the value for bs_user.status
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}