package edu.suse.bookstore.domain;

import java.io.Serializable;

public class UserRoleKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fk_user_role.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fk_user_role.role_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fk_user_role
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fk_user_role.user_id
     *
     * @return the value of fk_user_role.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fk_user_role.user_id
     *
     * @param userId the value for fk_user_role.user_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fk_user_role.role_id
     *
     * @return the value of fk_user_role.role_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fk_user_role.role_id
     *
     * @param roleId the value for fk_user_role.role_id
     *
     * @mbg.generated Sat May 30 16:53:27 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}